import type { Article, HashTag } from "@/types";

export const HASHTAGS: HashTag[] = [
  "politics",
  "conflict",
  "environment",
  "finance",
  "sports",
];

export const ARTICLES: Article[] = [
  // politics
  {
    id: "p1",
    title: "The ongoing debate on immigration policies and border security",
    source: "AP & Reuters",
    date: "2026-05-19",
    tag: "politics",
    image: "/images/article-placeholder-1.svg",
    bias: -0.19,
    lean: "left",
    href: "#",
  },
  {
    id: "p2",
    title: "A state visit reshapes regional alliances ahead of summit",
    source: "Reuters",
    date: "2026-05-18",
    tag: "politics",
    image: "/images/article-placeholder-2.svg",
    bias: 0.08,
    lean: "center",
    href: "#",
  },
  {
    id: "p3",
    title: "Mental health funding clears committee with bipartisan support",
    source: "NPR",
    date: "2026-05-18",
    tag: "politics",
    image: "/images/article-placeholder-3.svg",
    bias: -0.12,
    lean: "left",
    href: "#",
  },
  {
    id: "p4",
    title: "Senate hearing turns sharp over election security reforms",
    source: "WSJ",
    date: "2026-05-17",
    tag: "politics",
    image: "/images/article-placeholder-4.svg",
    bias: 0.21,
    lean: "right",
    href: "#",
  },
  {
    id: "p5",
    title: "Governors split on federal infrastructure funding formula",
    source: "Politico",
    date: "2026-05-16",
    tag: "politics",
    image: "/images/article-placeholder-1.svg",
    bias: -0.03,
    lean: "center",
    href: "#",
  },

  // conflict
  {
    id: "c1",
    title: "Ceasefire talks resume as humanitarian corridor opens",
    source: "BBC & AFP",
    date: "2026-05-17",
    tag: "conflict",
    image: "/images/article-placeholder-2.svg",
    bias: -0.06,
    lean: "center",
    href: "#",
  },
  {
    id: "c2",
    title: "Drone strike report contested by both sides at UN session",
    source: "Reuters",
    date: "2026-05-17",
    tag: "conflict",
    image: "/images/article-placeholder-1.svg",
    bias: 0.14,
    lean: "right",
    href: "#",
  },
  {
    id: "c3",
    title: "Aid convoys reach northern districts after week-long blockade",
    source: "Al Jazeera",
    date: "2026-05-16",
    tag: "conflict",
    image: "/images/article-placeholder-3.svg",
    bias: -0.18,
    lean: "left",
    href: "#",
  },
  {
    id: "c4",
    title: "Defense pact signals shift in regional security posture",
    source: "FT",
    date: "2026-05-15",
    tag: "conflict",
    image: "/images/article-placeholder-4.svg",
    bias: 0.11,
    lean: "right",
    href: "#",
  },
  {
    id: "c5",
    title: "Civilian casualty count disputed across rival agencies",
    source: "AP",
    date: "2026-05-14",
    tag: "conflict",
    image: "/images/article-placeholder-2.svg",
    bias: -0.04,
    lean: "center",
    href: "#",
  },

  // environment
  {
    id: "e1",
    title: "Coastal cities draft updated flood resilience plans",
    source: "The Guardian",
    date: "2026-05-17",
    tag: "environment",
    image: "/images/article-placeholder-3.svg",
    bias: -0.22,
    lean: "left",
    href: "#",
  },
  {
    id: "e2",
    title: "Wildfire season opens early in three western states",
    source: "Reuters",
    date: "2026-05-16",
    tag: "environment",
    image: "/images/article-placeholder-1.svg",
    bias: -0.09,
    lean: "center",
    href: "#",
  },
  {
    id: "e3",
    title: "Carbon market rules tighten after audit finds gaps",
    source: "Bloomberg",
    date: "2026-05-15",
    tag: "environment",
    image: "/images/article-placeholder-4.svg",
    bias: 0.05,
    lean: "center",
    href: "#",
  },
  {
    id: "e4",
    title: "Coral restoration project shows recovery in pilot zones",
    source: "NPR",
    date: "2026-05-14",
    tag: "environment",
    image: "/images/article-placeholder-2.svg",
    bias: -0.14,
    lean: "left",
    href: "#",
  },
  {
    id: "e5",
    title: "Permitting fight slows offshore wind buildout",
    source: "WSJ",
    date: "2026-05-13",
    tag: "environment",
    image: "/images/article-placeholder-3.svg",
    bias: 0.17,
    lean: "right",
    href: "#",
  },

  // finance
  {
    id: "f1",
    title: "Aviation regulators weigh new export rules amid sanctions",
    source: "Bloomberg",
    date: "2026-05-18",
    tag: "finance",
    image: "/images/article-placeholder-4.svg",
    bias: 0.19,
    lean: "right",
    href: "#",
  },
  {
    id: "f2",
    title: "Markets steady after central bank holds rates",
    source: "WSJ",
    date: "2026-05-16",
    tag: "finance",
    image: "/images/article-placeholder-1.svg",
    bias: 0.04,
    lean: "center",
    href: "#",
  },
  {
    id: "f3",
    title: "Bank earnings beat estimates as net interest margins widen",
    source: "FT",
    date: "2026-05-15",
    tag: "finance",
    image: "/images/article-placeholder-2.svg",
    bias: 0.07,
    lean: "center",
    href: "#",
  },
  {
    id: "f4",
    title: "Crypto custody bill advances with bipartisan amendments",
    source: "Reuters",
    date: "2026-05-14",
    tag: "finance",
    image: "/images/article-placeholder-3.svg",
    bias: -0.02,
    lean: "center",
    href: "#",
  },
  {
    id: "f5",
    title: "Housing affordability index hits new low in major metros",
    source: "AP",
    date: "2026-05-13",
    tag: "finance",
    image: "/images/article-placeholder-4.svg",
    bias: -0.16,
    lean: "left",
    href: "#",
  },

  // sports
  {
    id: "s1",
    title: "Underdog squad clinches playoff spot in final minutes",
    source: "ESPN",
    date: "2026-05-15",
    tag: "sports",
    image: "/images/article-placeholder-1.svg",
    bias: 0.0,
    lean: "center",
    href: "#",
  },
  {
    id: "s2",
    title: "Star forward returns from injury ahead of decisive series",
    source: "The Athletic",
    date: "2026-05-14",
    tag: "sports",
    image: "/images/article-placeholder-2.svg",
    bias: 0.01,
    lean: "center",
    href: "#",
  },
  {
    id: "s3",
    title: "League opens review into officiating after viral missed call",
    source: "ESPN",
    date: "2026-05-13",
    tag: "sports",
    image: "/images/article-placeholder-3.svg",
    bias: -0.05,
    lean: "center",
    href: "#",
  },
  {
    id: "s4",
    title: "Olympic qualifiers reshuffle field for 1500m final",
    source: "BBC",
    date: "2026-05-12",
    tag: "sports",
    image: "/images/article-placeholder-4.svg",
    bias: 0.02,
    lean: "center",
    href: "#",
  },
  {
    id: "s5",
    title: "Front office shakeup follows third straight first-round exit",
    source: "Sports Illustrated",
    date: "2026-05-11",
    tag: "sports",
    image: "/images/article-placeholder-1.svg",
    bias: -0.03,
    lean: "center",
    href: "#",
  },
];

export function articlesByTag(tag: HashTag): Article[] {
  const matches = ARTICLES.filter((a) => a.tag === tag);
  return matches.length > 0 ? matches : ARTICLES;
}
